import { motion, useReducedMotion } from "framer-motion";
import { useEffect, useState } from "react";
import { Outlet, useLocation } from "react-router-dom";
import { FlaskConical } from "lucide-react";
import { useHealth } from "../../api/hooks";
import { EASE } from "../../lib/motion";
import { Sidebar } from "./Sidebar";
import { Topbar } from "./Topbar";

export function Shell() {
  const [open, setOpen] = useState(false);
  const { pathname } = useLocation();
  const reduce = useReducedMotion();
  const health = useHealth();
  const demo = health.data?.data_label === "synthetic-demo";

  useEffect(() => { setOpen(false); window.scrollTo({ top: 0 }); }, [pathname]);

  return (
    <div className="app">
      <Sidebar open={open} onNavigate={() => setOpen(false)} />
      <div className={`scrim ${open ? "is-open" : ""}`} onClick={() => setOpen(false)} aria-hidden />
      <div className="main">
        <Topbar onMenu={() => setOpen(true)} />
        {demo && (
          <div className="demo-banner" role="note">
            <FlaskConical aria-hidden />
            <span><b>Demo mode — using synthetic data.</b> Every number in this instance comes from a dataset generated by the project, so it is illustrative only — not the reported results and not real demand.</span>
          </div>
        )}
        <main className="content" id="main">
          <motion.div key={pathname} initial={reduce ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.32, ease: EASE }}>
            <Outlet />
          </motion.div>
        </main>
      </div>
    </div>
  );
}
