"""Synthetic demo dataset (NOT real data).

Generates a made-up multi-store daily-orders dataset with the same schema and the same kinds of
structure the pipeline has to handle (weekly rhythm, closed days, promotions, holidays, school
closures, a slow trend, seasonality, stores with a gap in their history, a training-only column).
Nothing here is derived from any real dataset; every value comes from the random generator below.

    python scripts/make_synthetic_data.py        # writes data/synthetic/*.csv
"""
from __future__ import annotations

from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd

WEEKDAY_FACTOR = {1: 1.12, 2: 1.00, 3: 0.95, 4: 0.96, 5: 1.06, 6: 0.86, 7: 1.10}
MARKER = "SYNTHETIC_DATA.txt"
MARKER_TEXT = (
    "The CSV files in this directory are SYNTHETIC. They were generated by "
    "src/data/synthetic.py from a random number generator and are NOT the original dataset. "
    "Model results computed from them are demonstration values only.\n"
)


def make_synthetic_frames(n_stores: int = 120, n_train_days: int = 900, horizon: int = 42,
                          start: str = "2021-01-01", seed: int = 42) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Return (train, future, hub_metadata) frames with the pipeline's schema."""
    rng = np.random.RandomState(seed)
    dates = pd.date_range(start, periods=n_train_days + horizon, freq="D")
    stores = np.arange(1, n_stores + 1)
    grid = pd.MultiIndex.from_product([dates, stores], names=["Date", "HubID"]).to_frame(index=False)
    t = (grid["Date"] - dates[0]).dt.days.to_numpy()
    grid["Weekday"] = grid["Date"].dt.dayofweek + 1
    doy = grid["Date"].dt.dayofyear.to_numpy()

    # --- schedule (known in advance) ------------------------------------------------------
    open_sunday = rng.rand(n_stores) < 0.10                                   # most stores close on Sundays
    grid["IsOpen"] = np.where((grid["Weekday"] == 7) & ~open_sunday[grid["HubID"].to_numpy() - 1], 0, 1)
    holiday_days = rng.choice(len(dates), size=int(len(dates) * 0.03), replace=False)
    grid["RegionalHoliday"] = np.isin(t, holiday_days).astype(int)
    grid.loc[grid["RegionalHoliday"] == 1, "IsOpen"] = np.where(rng.rand((grid["RegionalHoliday"] == 1).sum()) < 0.6, 0, 1)
    store_phase = rng.randint(0, 2, n_stores)                                 # promotions alternate weeks, Mon-Fri
    week = t // 7
    grid["PromoActive"] = (((week + store_phase[grid["HubID"].to_numpy() - 1]) % 2 == 0) & (grid["Weekday"] <= 5)).astype(int)
    grid["SchoolClosureFlag"] = (((doy >= 200) & (doy <= 235)) | ((doy >= 355) | (doy <= 5))).astype(int)

    # --- demand ----------------------------------------------------------------------------
    level = rng.lognormal(np.log(4200), 0.35, n_stores)
    growth = rng.normal(0.02, 0.01, n_stores)                                  # per-year trend
    noise_level = rng.normal(0, 0.03, (len(dates), n_stores)).cumsum(axis=0) * 0.15   # slow store-specific drift
    noise_level = noise_level - noise_level.mean(axis=0)
    sid = grid["HubID"].to_numpy() - 1
    drift = noise_level[t, sid]
    demand = (
        level[sid]
        * (1 + growth[sid] * t / 365.0)
        * (1 + 0.08 * np.sin(2 * np.pi * doy / 365.25))
        * grid["Weekday"].map(WEEKDAY_FACTOR).to_numpy()
        * (1 + 0.32 * grid["PromoActive"].to_numpy())
        * (1 + 0.05 * grid["RegionalHoliday"].to_numpy())
        * (1 - 0.10 * grid["SchoolClosureFlag"].to_numpy())
        * np.exp(drift)
        * rng.lognormal(0.0, 0.13, len(grid))
    )
    grid["OrderVolume"] = np.round(demand * grid["IsOpen"].to_numpy()).astype(int)
    grid["AppSessions"] = np.round(grid["OrderVolume"] * rng.uniform(0.08, 0.12, len(grid))).astype(int)   # train-only

    train_end = dates[n_train_days - 1]
    train = grid[grid["Date"] <= train_end].copy()
    gap_stores = rng.choice(stores, size=max(1, n_stores // 10), replace=False)   # ~10% of stores lose a 120-day block
    drop = np.zeros(len(train), dtype=bool)
    tt = (train["Date"] - dates[0]).dt.days.to_numpy()
    for s in gap_stores:
        begin = rng.randint(60, 400)
        drop |= ((train["HubID"].to_numpy() == s) & (tt >= begin) & (tt < begin + 120))
    train = train[~drop].reset_index(drop=True)
    train = train[["HubID", "Weekday", "Date", "OrderVolume", "AppSessions", "IsOpen", "PromoActive",
                   "RegionalHoliday", "SchoolClosureFlag"]]

    future = grid[grid["Date"] > train_end].drop(columns=["OrderVolume", "AppSessions"]).reset_index(drop=True)
    future.insert(0, "Id", np.arange(1, len(future) + 1))
    future = future[["Id", "HubID", "Weekday", "Date", "IsOpen", "PromoActive", "RegionalHoliday", "SchoolClosureFlag"]]

    loyalty = rng.rand(n_stores) < 0.45
    has_comp = rng.rand(n_stores) < 0.75
    meta = pd.DataFrame({
        "HubID": stores,
        "HubFormat": rng.randint(1, 5, n_stores),
        "AssortmentTier": rng.randint(1, 4, n_stores),
        "CompetitorDistance": np.where(rng.rand(n_stores) < 0.03, np.nan, np.round(rng.lognormal(7.0, 1.0, n_stores), 0)),
        "CompetitorOpenSinceMonth": np.where(has_comp, rng.randint(1, 13, n_stores), np.nan),
        "CompetitorOpenSinceYear": np.where(has_comp, rng.randint(2005, 2020, n_stores), np.nan),
        "LoyaltyProgram": loyalty.astype(int),
        "LoyaltyProgramSinceWeek": np.where(loyalty, rng.randint(1, 53, n_stores), np.nan),
        "LoyaltyProgramSinceYear": np.where(loyalty, rng.randint(2012, 2020, n_stores), np.nan),
        "LoyaltyProgramInterval": np.where(loyalty, "Jan,Apr,Jul,Oct", None),
    })
    return train, future, meta


def write_synthetic_csvs(out_dir: Path, **kwargs) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    train, future, meta = make_synthetic_frames(**kwargs)
    train.to_csv(out_dir / "orders_train.csv", index=False)
    future.to_csv(out_dir / "orders_test.csv", index=False)
    meta.to_csv(out_dir / "hub_metadata.csv", index=False)
    (out_dir / MARKER).write_text(MARKER_TEXT)
    return out_dir
